// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/addPostQuery.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/api/postQuery.tsx";
import * as $5 from "./routes/api/userQuery.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/posts/add.tsx";
import * as $8 from "./routes/posts/index.tsx";
import * as $9 from "./routes/users.tsx";
import * as $10 from "./routes/users/add.tsx";
import * as $11 from "./routes/users/index.tsx";
import * as $$0 from "./islands/PostControls.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/addPostQuery.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/api/postQuery.tsx": $4,
    "./routes/api/userQuery.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/posts/add.tsx": $7,
    "./routes/posts/index.tsx": $8,
    "./routes/users.tsx": $9,
    "./routes/users/add.tsx": $10,
    "./routes/users/index.tsx": $11,
  },
  islands: {
    "./islands/PostControls.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
